# Generated by Django 4.2 on 2023-05-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_remove_complaint_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messsage',
            new_name='message',
        ),
    ]
